# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-04 06:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('RFL', 'Request for leave'), ('EL', 'Emergency leave'), ('OR', 'Other request')], default='RFL', max_length=3)),
                ('date_requested', models.DateTimeField(auto_now=True)),
                ('date_of_leave', models.DateTimeField(blank=True)),
                ('content', models.TextField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
