# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-26 09:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0002_auto_20170516_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Misc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('types', models.CharField(choices=[('recurring', 'Recurring'), ('fixed', 'Fixed')], default='recurring', max_length=150)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('months', models.PositiveIntegerField()),
                ('date_created', models.DateTimeField()),
                ('status', models.BooleanField(default=True)),
                ('employees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Misc',
            },
        ),
    ]
