# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-09 08:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'project',
            },
        ),
        migrations.CreateModel(
            name='ProjectAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_hours', models.FloatField()),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
            options={
                'verbose_name_plural': 'project-assignment',
            },
        ),
        migrations.CreateModel(
            name='WorkDiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished_task', models.CharField(max_length=200)),
                ('todo_task', models.CharField(max_length=200)),
                ('issues', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now=True)),
                ('hours', models.FloatField()),
                ('project_assignment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.ProjectAssignment')),
            ],
            options={
                'verbose_name_plural': 'workdiary',
            },
        ),
    ]
