# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-09 08:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workdiary',
            name='finished_task',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='workdiary',
            name='issues',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='workdiary',
            name='todo_task',
            field=models.TextField(),
        ),
    ]
