# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-01 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectassignment',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
