# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-04 06:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projects_hours_spent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workdiary',
            old_name='project_id',
            new_name='project',
        ),
    ]
