# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-09 03:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20170504_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='hours_spent',
        ),
    ]
