# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-19 07:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDiaryLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('work_diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.WorkDiary')),
            ],
        ),
    ]
