# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-09 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_projects_hours_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='hours_spent',
            field=models.FloatField(default=12),
            preserve_default=False,
        ),
    ]
