from django.conf.urls import url, include

from . import views


urlpatterns = [
    url(r'^request/create$', views.RequestView.as_view(), name='request'),
    url(r'^request/confirm$', views.UpdateRequest.as_view(), name='update_request'),
    url(r'^dashboard/$', views.AdminView.as_view(), name='admin'),
    url(r'^dashboard/search/$', views.AdminSearchView.as_view(), name='admin-search'),
    url(r'^account/confirm', views.ConfirmAccountView.as_view(), name='confirm_account'),
    url(r'^account/deactivate', views.DeactivateAccountView.as_view(), name='deactivate_account'),
    url(r'^employees/$', views.AllEmployeesView.as_view(), name='all_employees'),
    url(r'^attendance/$', views.AttendanceView.as_view(), name='attendance'),
    url(r'^attendance/search/$', views.AttendanceSearchView.as_view(), name='attendance-search'),
    url(r'^employee/(?P<id>[0-9]+)$', views.EmployeeProfileView.as_view(), name='employee_profile'),
    url(r'^requests/view$', views.ViewRequestsView.as_view(), name='view_all_requests'),
    url(r'^projects/(?P<id>[0-9]+)/$', views.ProjectManageView.as_view(), name='view_projects'),
    url(r'^payroll/$', views.ManagementPayrollView.as_view(), name='management_payroll'),
    url(r'^payroll/update$', views.ManagementPayrollView.as_view(), name='update_payroll'),
    url(r'^add/project/$', views.AddProjectView.as_view(), name='add_project'),
    url(r'^projects/(?P<id>[0-9]+)/assign/employee/$', views.AssignEmployeeView.as_view(), name='assign_employee'),
    url(r'^employee/(?P<emp_id>[0-9]+)/reports$', views.ViewReportsByEmployee.as_view(), name='reports_by_employee'),
    url(r'^edit/project/(?P<id>[0-9]+)/$', views.EditProjectView.as_view(), name='edit-project'),
    url(r'^edit/project/(?P<project_id>[0-9]+)/hours/(?P<id>[0-9]+)/$', views.EditHoursView.as_view(), name='edit-hours'),
    url(r'^edit/project/(?P<project_id>[0-9]+)/remove/employee/(?P<employee_id>[0-9]+)/$', views.RemoveEmployee.as_view(), name='remove-employee'),
    url(r'^edit/project/(?P<project_id>[0-9]+)/reassign/employee/(?P<employee_id>[0-9]+)/$', views.ReAssignEmployee.as_view(), name='reassign-employee'),
    url(r'^projects/$', views.ProjectListView.as_view(), name='project-list'),
    url(r'^projects/(?P<project_id>[0-9]+)/archive/project/$', views.ArchiveProjectView.as_view(), name='archive-project'),
    url(r'^projects/(?P<project_id>[0-9]+)/unarchive/project/$', views.UnArchiveProjectView.as_view(), name='unarchive-project'),
    url(r'search/', views.AdminGlobalSearch.as_view(), name='global-search'),
    url(r'^profile/$', views.ProfileAdminView.as_view(), name='admin_profile'),
    url(r'^change/password/$', views.ChangePasswordView.as_view(), name='change_password'),
    url(r'^misc/$', views.MiscView.as_view(), name='admin_misc'),
    url(r'^misc/(?P<misc_id>[0-9]+)/employee/$', views.MiscEmployeeView.as_view(), name='employee_misc'),
    url(r'^misc/add/$', views.AddMiscView.as_view(), name='add_misc'),
    url(r'^misc/edit/(?P<misc_id>[0-9]+)/$', views.EditMiscView.as_view(), name='edit_misc'),
    url(r'^misc/(?P<misc_id>[0-9]+)/archive/$', views.ArchiveMiscView.as_view(), name='archive_misc'),
    url(r'^misc/(?P<misc_id>[0-9]+)/unarchive/$', views.UnArchiveMiscView.as_view(), name='unarchive_misc'),
]
