# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-08 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=20),
            preserve_default=False,
        ),
    ]
