# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-09 03:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_payroll_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='amount',
        ),
    ]
