# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-15 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_hourly_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='date_generated',
        ),
        migrations.AddField(
            model_name='payroll',
            name='invoice_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
