# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-03 03:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170502_1519'),
        ('accounts', '0002_auto_20170502_1948'),
    ]

    operations = [
    ]
